
<form enctype="multipart/form-data" action="/convert/upload/auth/videomonitoring/type/qam" method="POST">

What file format are you going to use?<br/>
<input type="radio" name="format" value="excel_2003">Excel 2003<br/>
<input type="radio" name="format" value="csv">CSV<br/>
<input type="radio" name="format" value="text">Text File<br/><br/>

<input type="hidden" name="MAX_FILE_SIZE" value="100000000000" />
Choose a file to upload: <input name="uploadedfile" type="file" /><br />
<input type="submit" value="Upload File" />
</form>
