<?php

//Chart Parameters
$chart = urlencode( $this->input_chart );
//$data_source = urlencode( $input_data_source );
//$caption = urlencode( $input_title );
//$subcaption = "";
//$labelstep = urlencode( $input_labelstep );
$width = $this->width;
$height = $this->height;

// URL that will return the XML data for the fusionchart
$data_url = $this->data_url; //"/charts/demo/Data1.xml";
?>


<html>

<SCRIPT LANGUAGE="Javascript" SRC="/charts/FusionCharts/JSClass/FusionCharts.js">
//You need to include the above JS file, if you intend to embed the chart using JavaScript.
</SCRIPT>

<SCRIPT LANGUAGE="JavaScript">

function FC_Rendered(DOMId){
   //This method is called whenever a FusionCharts chart is loaded.
   //Check if it's the required chart using ID
   if (DOMId=="ChId1"){
       //Invoke updateChart() method to update chart with new data       
	updateChart();
   }
}

function updateChart(){
   //Get reference to chart object using Dom ID "ChId1"
   var chartObj = getChartFromId("ChId1");
   
    var strURL = "<?php echo $data_url; ?>";

    //strURL = strURL + "&currTime=" + getTimeForURL();
    //This basically adds a ever-changing parameter which bluffs
    //the browser and forces it to re-load the XML data every time.

   //Update its XML Data URL
   chartObj.setDataURL( strURL );
}
</SCRIPT>

<BODY>
<div id="chart1div">
    This Chart Needs Falsh.
</div>
<script type="text/javascript">
   var chart1 = new FusionCharts("/charts/Charts/<?php echo $chart; ?>", "ChId1", "<?php echo $width; ?>", "<?php echo $height; ?>", "0", "1");
   //Start Chart with empty data as we'll later update using JavaScript
   chart1.setDataXML("<chart></chart>");
   chart1.render("chart1div");
</script>
</BODY>

</html>

