<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <title>Customer List</title>
    <link rel="stylesheet" type="text/css" href="/extjs/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="/extjs/css/grid-examples.css" />
    <!-- Common Styles for the examples -->
    <link rel="stylesheet" type="text/css" href="/extjs/css/examples.css" />
    <link rel="stylesheet" type="text/css" href="/extjs/css/RowEditor.css" />

	<style type="text/css">
		.x-grid3 .x-window-ml{
			padding-left: 0;	
		} 
		.x-grid3 .x-window-mr {
			padding-right: 0;
		} 
		.x-grid3 .x-window-tl {
			padding-left: 0;
		} 
		.x-grid3 .x-window-tr {
			padding-right: 0;
		} 
		.x-grid3 .x-window-tc .x-window-header {
			height: 3px;
			padding:0;
			overflow:hidden;
		} 
		.x-grid3 .x-window-mc {
			border-width: 0;
			background: #cdd9e8;
		} 
		.x-grid3 .x-window-bl {
			padding-left: 0;
		} 
		.x-grid3 .x-window-br {
			padding-right: 0;
		}
		.x-grid3 .x-panel-btns {
			padding:0;
		}
		.x-grid3 .x-panel-btns td.x-toolbar-cell {
			padding:3px 3px 0;
		}
		.x-box-inner {
			zoom:1;
		}
        .icon-user-add {
            background-image: url(/extjs/pic/user_add.gif) !important;
        }
        .icon-user-delete {
            background-image: url(/extjs/pic/user_delete.gif) !important;
        }        
    </style>
    
    <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"> </script><script type="text/javascript">_uacct = "UA-1396058-1";urchinTracker();</script><!-- LIBS -->
    <script type="text/javascript" src="/extjs/ext-base.js"></script>
    <script type="text/javascript" src="/extjs/ext-all.js"></script>
    <script type="text/javascript" src="/extjs/gen-names.js"></script>
    <script type="text/javascript" src="/extjs/RowEditor.js"></script>
    <!--<script type="text/javascript" src="/extjs/row-editor.js"></script>-->
    <script type="text/javascript" src="/extjs/Ext.ux.util.js"></script>
    <script type="text/javascript" src="/extjs/Ext.ux.grid.Search.js"></script>

    <script type="text/javascript">

	Ext.onReady(function(){

		//Ext.Msg.alert('Status', 'Changes saved successfully.');

		// Used for adding a record into the grid
		var Customer = Ext.data.Record.create([
			{ name: 'name', type: 'string' },
			{ name: 'contact', type: 'string' },
			{ name: 'address', type: 'string' },
			{ name: 'city', type: 'string' },
			{ name: 'state', type: 'string' },
			{ name: 'zip', type: 'string' },
			{ name: 'phone_number', type: 'string' },
		]);

		// Create the inline editor
		var editor = new Ext.ux.grid.RowEditor({
        		saveText: 'Update'
    		});

		var search = new Ext.ux.grid.Search({
				iconCls:'icon-zoom'
				//,readonlyIndexes:['note']
				//,disableIndexes:['pctChange']
				,minChars:2
				,autoFocus:true
//				,menuStyle:'radio'
			});

		// create the data store
		var store = new Ext.data.JsonStore({
			url: '/customers/indexget',
			fields: [
				{name: 'company_id_seq', type: 'int'},
				'name', 'contact', 'address', 'city', 'state', 'zip', 'phone_number' 
			]
		});
	
		// load data from the url 
		store.load();

		// create the Grid
		var grid = new Ext.grid.GridPanel({
			store: store,
			plugins: [editor],
			columns: [
				new Ext.grid.RowNumberer(),
				{id:'company_id_seq',header: 'ID', width: 30, sortable: true, dataIndex: 'company_id_seq'},
				{header: 'Name', width: 150, sortable: true, dataIndex: 'name', editor: { xtype: 'textfield', allowBlank: false } },
				{header: 'Contact', width: 80, sortable: true, dataIndex: 'contact', editor: { xtype: 'textfield', allowBlank: false } },
				{header: 'Address', width: 150, sortable: true, dataIndex: 'address', editor: { xtype: 'textfield', allowBlank: false } },
				{header: 'City', width: 90, sortable: true, dataIndex: 'city', editor: { xtype: 'textfield', allowBlank: false } },
				{header: 'State', width: 40, sortable: true, dataIndex: 'state', editor: { xtype: 'textfield', allowBlank: false } },
				{header: 'Zip', width: 80, sortable: true, dataIndex: 'zip', editor: { xtype: 'textfield', allowBlank: false } },
				{header: 'Phone Number', width: 90, sortable: true, dataIndex: 'phone_number', editor: { xtype: 'textfield', allowBlank: false } }
			],
			stripeRows: true,
			//height:250,
			autoHeight: true,
			//width:900,
			autoWidth: true,
			autoScroll: true,
			title:'Customer List',
			tbar: [{
            			iconCls: 'icon-user-add',
            			text: 'Add',
            			handler: function(){
                			var e = new Customer({
                    				name: '',
                    				contact: '',
                    				address: '',
						city: '',
						state: '',
						zip: '',
						phone_number: ''
                			});
                			editor.stopEditing();

					// Add our new record as the first row, select it
                			store.insert(0, e);
                			grid.getView().refresh();
                			grid.getSelectionModel().selectRow(0);

					// Start editing the new row
                			editor.startEditing(0);
            			}
        		},{
            			ref: '../removeBtn',
            			iconCls: 'icon-user-delete',
            			text: 'Remove',
            			disabled: true,
            			handler: function(){
                			editor.stopEditing();
					var s = grid.getSelectionModel().getSelected();
					var id_seq = s.get( 'id_seq' );
					// Delete Selected
					Ext.Ajax.request({
						url: '/customers/softwaredelete/id_seq/' + id_seq,
						method: 'GET',
						success: function(){
							store.reload();
						}
					});
            			}
        		},{
                                iconCls: 'icon-user-delete',
                                text: 'Go Software',
                                disabled: false,
                                handler: function(){
					// Capture the button click then get which row it is on
					var s = grid.getSelectionModel().getSelected();
					var company_id_seq = s.get( 'company_id_seq' );
					var name = s.get( 'name' );
					//Ext.Msg.alert('Status', company_id_seq);	
					window.location = '/customers/software/id/' + company_id_seq + '/name/' + name;
                                }
                        },{
                                iconCls: 'icon-user-delete',
                                text: 'Go Probe',
                                disabled: false,
                                handler: function(){
                                        // Capture the button click then get which row it is on
                                        var s = grid.getSelectionModel().getSelected();
                                        var company_id_seq = s.get( 'company_id_seq' );
					var name = s.get( 'name' );
                                        //Ext.Msg.alert('Status', company_id_seq);      
                                        window.location = '/customers/probe/id/' + company_id_seq + '/name/' + name;
                                }
                        },{
                                iconCls: 'icon-user-delete',
                                text: 'Go Extra Services',
                                disabled: false,
                                handler: function(){
                                        // Capture the button click then get which row it is on
                                        var s = grid.getSelectionModel().getSelected();
                                        var company_id_seq = s.get( 'company_id_seq' );
					var name = s.get( 'name' );
                                        //Ext.Msg.alert('Status', company_id_seq);      
                                        window.location = '/customers/extra/id/' + company_id_seq + '/name/' + name;
                                }
                        }] // End of tbar
		}); // End of GridPanel

		// Listener for after editing a row
		editor.on({
			scope: this,
			afteredit: function(roweditor, changes, record, rowIndex) {
				Ext.Ajax.request({
					url: '/customers/indexadd/customer_id_seq/' + record.get( 'company_id_seq' ),
					method: 'GET',
					params: changes,
					success: function(){
						store.reload();	
					}
				});
			}
		});

		// render grid
		grid.render('the-grid');
	});
    </script>
</head>
<body>
	<table border="0" width="100%">
		<tr><td>User: <? echo $this->user ?></td><td><!--<a href="/login/logout">Logout</a>--></td></tr>
	</table>
	<div id="the-grid"></div>

	<iframe src ="http://zend1.grep-r.com/reporting/pie3d/width/400/height/400?data=/data/index/class/customerreporting/method/probe_type_pie/caption/Probe%20Type%20Breakout/subcaption/Across%20All%20Customers/xAxisName/x%20name/yAxisName/y%20name/numberPrefix//none/" frameborder="0" width="450" height="450">
  	<p>Your browser does not support iframes.</p>
	</iframe>
	<iframe src ="http://zend1.grep-r.com/reporting/pie3d/width/400/height/400?data=/data/index/class/customerreporting/method/software_type_pie/caption/Software%20Type%20Breakout/subcaption/Across%20All%20Customers/xAxisName/x%20name/yAxisName/y%20name/numberPrefix//none/" frameborder="0" width="450" height="450">
        <p>Your browser does not support iframes.</p>
        </iframe>
</body>
</html>
