<form action="/probe/adduser/auth/videomonitoring" method="post">

Probe's IP:<input type="text" name="probe-ip"/><br/>
Probes's Login:<input type="text" name="probe-username"/><br/>
Probes's Password:<input type="text" name="probe-password"/><br/>
New User:<input type="text" name="new-user"/><br/>
New Pass:<input type="text" name="new-pass"/><br/>
New Group<input type="text" name="group"/>public | private | admin<br/>
<input type="submit" name="submit"/>
</form>
